app:
  meta:
    version: 1.0.0
    name: Catalyst Service
logging:
  level: debug
  format: pretty
databases:
  connections:
    serhafen-us:
      host: ${DB_BU1_US_HOST:localhost}
      port: ${DB_BU1_US_PORT:5432}
      username: ${DB_BU1_US_USERNAME:postgres}
      password: ${DB_BU1_US_PASSWORD}
      database: ${DB_BU1_US_DATABASE:serhafen_common}
      schema: ${DB_BU1_US_SCHEMA:us}
    serhafen-ag:
      host: ${DB_BU1_AG_HOST:localhost}
      port: ${DB_BU1_AG_PORT:5432}
      username: ${DB_BU1_AG_USERNAME:postgres}
      password: ${DB_BU1_AG_PASSWORD}
      database: ${DB_BU1_AG_DATABASE:serhafen_common}
      schema: ${DB_BU1_AG_SCHEMA:ag}
    serhafen-cl:
      host: ${DB_BU2_CL_HOST:localhost}
      port: ${DB_BU2_CL_PORT:5432}
      username: ${DB_BU2_CL_USERNAME:postgres}
      password: ${DB_BU2_CL_PASSWORD}
      database: ${DB_BU2_CL_DATABASE:serhafen_chile}
      schema: ${DB_BU2_CL_SCHEMA:cl}
  pool:
    maxConnections: ${DB_POOL_MAX:10}
    minConnections: ${DB_POOL_MIN:1}
    idleTimeoutMillis: ${DB_POOL_IDLE_TIMEOUT:10000}
    connectionTimeoutMillis: ${DB_POOL_CONNECTION_TIMEOUT:10000}
aws:
  region: ${AWS_REGION:us-east-1}
  sns:
    useStaticCredentials: ${SNS_USE_STATIC_CREDENTIALS:false}
    accessKeyId: ${SNS_ACCESS_KEY_ID:test}
    secretAccessKey: ${SNS_SECRET_ACCESS_KEY:test}
    sessionToken: ${SNS_SESSION_TOKEN:test}
    endpoint: ${SNS_ENDPOINT}
  sqs:
    useStaticCredentials: ${SQS_USE_STATIC_CREDENTIALS:false}
    accessKeyId: ${SQS_ACCESS_KEY_ID:test}
    secretAccessKey: ${SQS_SECRET_ACCESS_KEY:test}
    sessionToken: ${SQS_SESSION_TOKEN:test}
    endpoint: ${SQS_ENDPOINT}
    defaultWaitTimeSeconds: ${SQS_DEFAULT_WAIT_TIME_SECONDS:20}
    defaultVisibilityTimeout: ${SQS_DEFAULT_VISIBILITY_TIMEOUT:60}
    defaultMaxNumberOfMessages: ${SQS_DEFAULT_MAX_NUMBER_OF_MESSAGES:10}
clients:
  sample:
    baseUrl: ${SAMPLE_CLIENT_BASE_URL:https://01k6ymddesw4aqq39m5fcyehm300-ae84886dace71b7e4e76.requestinspector.com}
    circuitBreaker:
      timeout: ${SAMPLE_CLIENT_CIRCUIT_BREAKER_TIMEOUT:5000}
      errorThresholdPercentage: ${SAMPLE_CLIENT_CIRCUIT_BREAKER_ERROR_THRESHOLD_PERCENTAGE:10}
      resetTimeout: ${SAMPLE_CLIENT_CIRCUIT_BREAKER_RESET_TIMEOUT:30000}
queues:
  example:
    name: dummy-queue
